development:
  adapter: postgresql
  encoding: unicode
  database: ghostcake
  pool: 5
  username: machine
  password: 
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: ghostcake_test
  username: postgres

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ghostcake
  pool: 5
  username: ghostcake
  password: password
